-- 코드를 입력하세요
SELECT T2.AUTHOR_ID,
T3.AUTHOR_NAME,
T2.CATEGORY,
SUM(T1.TOTAL_SALES * T2.PRICE) SALES
FROM
(SELECT BOOK_ID,
SUM(SALES) TOTAL_SALES
FROM 
(SELECT *
FROM BOOK_SALES
WHERE SALES_DATE LIKE '2022-01%') AS T1
GROUP BY BOOK_ID) AS T1
JOIN BOOK AS T2 ON T1.BOOK_ID = T2.BOOK_ID
JOIN AUTHOR AS T3 ON T2.AUTHOR_ID = T3.AUTHOR_ID
GROUP BY T2.AUTHOR_ID, T2.CATEGORY
ORDER BY 1, 3 DESC;