-- 코드를 입력하세요
SELECT CAR.CAR_ID,
CAR.CAR_TYPE,
ROUND(CAR.DAILY_FEE * 30 * (100 - DISCOUNT.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DISCOUNT
ON CAR.CAR_TYPE = DISCOUNT.CAR_TYPE
AND DISCOUNT.DURATION_TYPE = '30일 이상'
WHERE 1=1 
AND CAR.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30'
    AND END_DATE >= '2022-11-01'
)
AND CAR.CAR_TYPE IN ('세단', 'SUV')
HAVING FEE >= 500000
AND FEE < 2000000
ORDER BY 3 DESC, 2, 1 DESC;
