-- 코드를 입력하세요
SELECT YEAR, 
MONTH, 
GENDER,
COUNT(USER_ID) USERS
FROM (
    SELECT DISTINCT YEAR(OS.SALES_DATE) YEAR,
    MONTH(OS.SALES_DATE) MONTH,
    UI.GENDER GENDER,
    UI.USER_ID
    FROM ONLINE_SALE OS
    JOIN USER_INFO UI
    ON OS.USER_ID = UI.USER_ID
    WHERE UI.GENDER IS NOT NULL
) T
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1, 2, 3