-- 코드를 작성해주세요
WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT T1.ID, T1.PARENT_ID, CTE.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA T1
    JOIN CTE ON T1.PARENT_ID = CTE.ID
)
SELECT COUNT(*) COUNT, GENERATION
FROM CTE
WHERE ID NOT IN
(
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION