-- 코드를 입력하세요
SELECT CAR_ID,
CASE
    WHEN AVAILABILITY > 0 THEN '대여중'
    ELSE '대여 가능'
END AVAILABILITY
FROM 
(SELECT CAR_ID, SUM(AVAILABILITY) AVAILABILITY
FROM
(SELECT CAR_ID,
CASE
    WHEN STR_TO_DATE('20221016', '%Y%m%d') BETWEEN START_DATE AND END_DATE THEN 1
    ELSE 0
END AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS T1
GROUP BY CAR_ID) AS T2
ORDER BY 1 DESC