-- 코드를 입력하세요
SELECT T1.WRITER_ID USER_ID,
T2.NICKNAME,
SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD T1
JOIN USED_GOODS_USER T2
ON T1.WRITER_ID = T2.USER_ID
AND T1.STATUS = 'DONE'
GROUP BY T1.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY 3