-- 코드를 작성해주세요
SELECT T1.EMP_NO,
T1.EMP_NAME,
T1.GRADE,
CASE
    WHEN (T1.GRADE = 'S') THEN T2.SAL * 0.2
    WHEN (T1.GRADE = 'A') THEN T2.SAL * 0.15
    WHEN (T1.GRADE = 'B') THEN T2.SAL * 0.1
    ELSE 0
END BONUS
FROM (SELECT EMP.EMP_NO,
EMP.EMP_NAME,
CASE
    WHEN (SUM(GRD.SCORE) / 2) >= 96 THEN 'S'
    WHEN (SUM(GRD.SCORE) / 2) >= 90 THEN 'A'
    WHEN (SUM(GRD.SCORE) / 2) >= 80 THEN 'B'
    ELSE 'C'
END GRADE
FROM HR_EMPLOYEES EMP
JOIN HR_GRADE GRD ON EMP.EMP_NO = GRD.EMP_NO
GROUP BY EMP.EMP_NO) AS T1
JOIN HR_EMPLOYEES T2 ON T1.EMP_NO = T2.EMP_NO
ORDER BY 1