SELECT T1.ITEM_ID, T1.ITEM_NAME, T1.RARITY
FROM ITEM_INFO T1
JOIN (SELECT T2.ITEM_ID
      FROM ITEM_INFO T1
      JOIN ITEM_TREE T2 
      ON T1.ITEM_ID = T2.PARENT_ITEM_ID
      AND T1.RARITY = 'RARE') AS T2
ON T1.ITEM_ID = T2.ITEM_ID
ORDER BY 1 DESC;