-- 코드를 작성해주세요
WITH CTE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR,
    MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT T2.YEAR,
T2.MAX_SIZE - T1.SIZE_OF_COLONY YEAR_DEV,
T1.ID
FROM ECOLI_DATA T1
JOIN CTE T2 
ON YEAR(T1.DIFFERENTIATION_DATE) = T2.YEAR
ORDER BY 1, 2