SELECT T1.ID, T2.FISH_NAME, T1.LENGTH
FROM (SELECT T1.ID, T1.FISH_TYPE, T1.LENGTH
      FROM FISH_INFO AS T1
      JOIN (SELECT FISH_TYPE,
            MAX(LENGTH) MAX_LENGTH
            FROM FISH_INFO
            GROUP BY FISH_TYPE) AS T2
      ON T1.FISH_TYPE = T2.FISH_TYPE
      AND T1.LENGTH = T2.MAX_LENGTH) AS T1
JOIN FISH_NAME_INFO AS T2
ON T1.FISH_TYPE = T2.FISH_TYPE
ORDER BY 1