-- 코드를 입력하세요
SELECT I.CATEGORY,
SUM(TOTAL_SALES) TOTAL_SALES
FROM
(SELECT BOOK_ID,
SUM(SALES) TOTAL_SALES
FROM BOOK_SALES
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY BOOK_ID) S
JOIN BOOK I ON S.BOOK_ID = I.BOOK_ID
GROUP BY I.CATEGORY
ORDER BY 1